#!/bin/sh

log="$PWD/output.log"
echo "Writing command output to $log"

quiet() {
  (
    echo "Running: $@"
    "$@"
  ) >> $log 2>&1
}

try() {
  path="$1" 
  shift

  (
    cd "$path"
    quiet "$@"
  )

  status=$?
  name="$(basename "$path")"
  if [ $status -eq 0 ] ; then
    echo "OK: $name $@"
  else
    echo "FAIL: $name $@"
  fi
  return $status
}

rbenv global jruby-1.7.26

version="$(ruby --version)"
if ! quiet ruby --version ; then
  echo "No ruby executable found?"
  exit 1
fi

if ! ruby --version | grep -q '^jruby ' ; then
  echo "Ruby must be JRuby"
  exit 1
fi

# We assume all plugins are checked out to 
for path in $(ls -d tmp/*/); do
  basename "$path"
  try "$path" bundle install || continue
  try "$path" bundle exec rake vendor || continue
  try "$path" bundle exec rspec || continue
  try "$path" bundle exec rake publish_gem
done
